from __future__ import annotations

from typing import Protocol


class EmailClient(Protocol):
    def read_inbox(self, limit: int) -> list[dict]: ...
    def save_draft(self, to: list[str], subject: str, body: str) -> str: ...
    def send(self, to: list[str], subject: str, body: str) -> str: ...


class CalendarClient(Protocol):
    def list_events(self, day: str) -> list[dict]: ...
    def create_event(self, title: str, start: str, end: str, attendees: list[str]) -> str: ...
    def accept_invite(self, event_id: str) -> str: ...
